"""empty message

Revision ID: e04b7d489573
Revises: a3d78ee1e68b
Create Date: 2018-11-18 05:56:28.458469

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e04b7d489573"
down_revision = "a3d78ee1e68b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("password", sa.String(length=255)))
    op.execute("UPDATE users SET password=email")
    op.alter_column("users", "password", nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "password")
    # ### end Alembic commands ###
